//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class News
    {
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public int Id { get; set; }
        public string Discriminator { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public string EmployeeId { get; set; }
        public bool IsPublished { get; set; }
        public string TextContent { get; set; }
        public string Title { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Document Document { get; set; }
    }
}
