//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Quizz
    {
        public int Id { get; set; }
        public bool IsPublished { get; set; }
        public string QuizzUrl { get; set; }
        public int Semester { get; set; }
        public int Year { get; set; }
    }
}
