//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDbTest
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class BilateralProtocol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BilateralProtocol()
        {
            this.Applications = new ObservableCollection<Application>();
            this.Applications1 = new ObservableCollection<Application>();
            this.Applications2 = new ObservableCollection<Application>();
        }
    
        public int Id { get; set; }
        public string Destination { get; set; }
        public int OpenSlots { get; set; }
        public int SubjectId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Application> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Application> Applications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Application> Applications2 { get; set; }
        public virtual CollegeSubject CollegeSubject { get; set; }
    }
}
