//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDbTest
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class CollegeSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollegeSubject()
        {
            this.AspNetUsers = new ObservableCollection<AspNetUser>();
            this.BilateralProtocols = new ObservableCollection<BilateralProtocol>();
        }
    
        public int Id { get; set; }
        public int CollegeId { get; set; }
        public string SubjectAlias { get; set; }
        public string SubjectName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<BilateralProtocol> BilateralProtocols { get; set; }
        public virtual College College { get; set; }
    }
}
